server:
  port: 7001

spring:
  application:
    name: product-composite-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-composite-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

product:
  service:
    url: http://product

review:
  service:
    url: http://review

recommendation:
  service:
    url: http://recommendation

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092

product:
  service:
    url: http://product

review:
  service:
    url: http://review

recommendation:
  service:
    url: http://recommendation
